on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 13 * * 5"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.4"
      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          chmod +x installResources.sh
          ./installResources.sh

      - name: Build app with PyInstaller
        run: |
          pyinstaller --onefile --hidden-import=yaml,xmltodict main.py

      - name: Archive compiled app
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: dist/main.exe
